import { createHash } from 'node:crypto';

export const VOICE_PACKS = [
  {
    id: 'bella',
    label: 'Cornerwork Bella',
    description: 'Clear female coach',
    modelVoice: 'af_bella',
  },
  {
    id: 'michael',
    label: 'Cornerwork Michael',
    description: 'Clear male coach',
    modelVoice: 'am_michael',
  },
];

const numbers = Array.from({ length: 31 }, (_, value) => String(value));

const core = [
  'Round',
  'Level',
  'Point',
  'Points',
  'And',
  'Body',
  'Head',
  'Rest',
  'Long recovery',
  'Open boxing',
  'Warmup. Get ready.',
  'Punch out',
  'Back to boxing',
  'Workout complete. Great work.',
  'Endless run complete.',
  'Jab',
  'Cross',
  'Left hook',
  'Right hook',
  'Left uppercut',
  'Right uppercut',
  'Jab to body',
  'Cross to body',
  'Left hook to body',
  'Right hook to body',
  'Angle out',
  'Check kick',
  'Front kick',
  'Guard',
  'Jab feint',
  'Left elbow',
  'Right elbow',
  'Left kick',
  'Right kick',
  'Left knee',
  'Right knee',
  'Pivot',
  'Pull',
  'Roll',
  'Roll left',
  'Roll right',
  'Shuffle back',
  'Shuffle forward',
  'Slip',
  'Slip left',
  'Slip right',
  'Slip outside',
  'Step back',
  'Step in',
  'Step out',
];

const focuses = [
  'Jab variations',
  'Cross focus',
  'Hook focus',
  'Repeat combination',
  'Focus jabs',
  'Straight punches',
  'Hooks',
  'Short combos',
  'Mix up combos',
  'Explosive bursts',
  'Punch-out 15 seconds',
  'Punch-out 30 seconds',
  'High intensity',
  'Speed',
  'Power',
  'Defense and counters',
  'Footwork and angles',
  'Movement',
  'Body work',
  'Head to body',
  'Body to head',
  'Enter and exit',
  'Counter after defense',
  'Finish with defense',
  'Finish with footwork',
  'Double lead hand',
  'Rear-hand counters',
  'Moving backward',
  'Cut off the ring',
  'Long-range boxing',
  'Uppercuts',
  'Inside fighting',
  'Kicks',
  'Punch to kick',
  'Knees and elbows',
  'Kickboxing flow',
  'Freestyle',
];

const coaching = [
  'Hands back to guard',
  'Move after the combination',
  'Change levels',
  'Relax your shoulders',
  'Breathe with every punch',
  'Finish with an angle',
  'Turn the punch over',
  'Drive through the target',
  'Do not push the bag',
  'Reset after the power shot',
  'Keep the bag under control',
  'Visualize your opponent',
  'Stay balanced while moving',
  'Finish at an angle',
  'Keep your feet under you',
  'Make the defense small',
  'Keep your chin tucked',
  'Return every punch to guard',
  'Stay balanced',
  'Exhale on each punch',
  'Keep your hands relaxed',
  'Circle left',
  'Circle right',
  'Reset your stance',
  'Move your head',
  'Change angle',
  'Feint',
  'Keep your guard up',
  'Breathe slowly',
  'Shake out your shoulders',
  'Stay loose',
  'Deep breath and recover',
  'Keep moving lightly',
  'Keep the pace',
  'Stay sharp and keep going',
  'Strong work. Stay with it.',
  'One combination at a time',
  'Breathe and keep moving',
  'Good rhythm. Do not fade.',
  'Stay composed as the level builds',
  'Level cleared. Breathe and reset.',
  'Good work. Recover for the next level.',
  'Stay loose. The next level is coming.',
  'Control your breathing and keep moving',
  'Reset your guard and get ready',
];

const focusedDrills = [
  'High-low straights',
  'Hook workshop',
  'Speed and power calls',
  'Footwork entries',
  'Repeat each assignment at a controlled pace until the next callout. Return the lead hand to guard and keep moving between repetitions.',
  'Repeat the called straight-punch pattern until the next callout. Change level with your knees for body shots and return both hands to guard.',
  'Repeat the called hook pattern until the next callout. Keep the punches compact, rotate through your feet, and protect your chin with the opposite hand.',
  'Work close to the bag and repeat the assignment until the next callout. Keep hooks and uppercuts short, stay balanced, and reset your guard after every combination.',
  'Follow the effort named and keep working until the next callout. Technique means controlled clean punches, speed means fast light punches, power means strong balanced shots, and movement means active recovery around the bag.',
  'Imagine the incoming punch, perform the defense first, then throw the counter. Repeat the complete reaction until the next callout and return to your stance each time.',
  'Repeat the complete movement and punch assignment until the next callout. Keep your feet from crossing and finish every repetition balanced in your boxing stance.',
  'One to the head',
  'One to the body',
  'One feint',
  'One feint. One two.',
  'One two to the head',
  'One body. Two head.',
  'One head. Two body.',
  'Three to the head',
  'Three to the body',
  'Four to the body',
  'Three body. Three head.',
  'Three four to the head',
  'Five six',
  'Three body. Five. Three head.',
  'Six three',
  'Technique. One two.',
  'Speed. One two.',
  'Power. Two.',
  'Movement and jab',
  'Slip right. Two.',
  'Slip left. Three.',
  'Catch. One two.',
  'Roll. Three two.',
  'Pull. Two.',
  'Step in. One.',
  'Double one moving forward',
  'One. Circle left.',
  'One two. Pivot out.',
  'One. Step out.',
];

export function normalizeVoiceLine(value) {
  return String(value)
    .toLowerCase()
    .replace(/[’']/g, '')
    .replace(/&/g, ' and ')
    .replace(/\bsecs?\b/g, 'seconds')
    .replace(/[·–—-]/g, ' ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ');
}

const unique = new Map();
for (const text of [...numbers, ...core, ...focuses, ...coaching, ...focusedDrills]) {
  const key = normalizeVoiceLine(text);
  if (key && !unique.has(key)) unique.set(key, String(text).trim());
}

export const VOICE_LINES = [...unique].map(([key, text]) => ({
  id: createHash('sha1').update(key).digest('hex').slice(0, 12),
  key,
  text,
}));
